language: c
sudo: true
addons:
  apt:
    packages:
      - build-essential
      - doxygen
      - graphviz
before_install:
  - sudo apt-get install -y linux-headers-`uname-r`
script:
  - make
  - make doc
  - make clean
notifications:
  on_success: never
  on_failure: never
