language: c
sudo: required
group: deprecated-2017Q1
addons:
  apt:
    packages:
      - build-essential
      - doxygen
      - graphviz
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y linux-headers-generic
script:
  - make -C 00.hello   && make -C 00.hello   doc && make -C 00.hello   clean
  - make -C 01.ktimer  && make -C 01.ktimer  doc && make -C 01.ktimer  clean
  - make -C 02.hrtimer && make -C 02.hrtimer doc && make -C 02.hrtimer clean
notifications:
  on_success: never
  on_failure: never
